name: release-images

on:
  pull_request:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY_SERVER_ADDRESS: ghcr.io/tricorder-observability
  REGISTRY_USER_NAME: ${{ github.repository_owner }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}

jobs:
  release-images:
    # This matches the dev_image and base image used in the code base.
    runs-on: ubuntu-22.04
    container:
      image: public.ecr.aws/tricorder/ci_image:202302140538
      options: --privileged
      volumes:
        # Needed for accessing kernel headers
        # TODO(yzhao): Need to add the ability to install kernel headers.
        - /lib/modules:/lib/modules
        # Needed to access /sys/kernel/tracing/kprobe
        - /sys/kernel:/sys/kernel
        # Needed for accessing kernel headers
        - /usr/src:/usr/src
    permissions:
      contents: read
      packages: write
    timeout-minutes: 90
    env:
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/v})"
      - name: Print container tag
        run: echo "Running release build for ${{ steps.extract_tag.outputs.tag }}"
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACTIONS_TOKEN }}
      - name: Build and push tailing sidecar multiplatform image
        run: bazel run -c opt --define=TAG=${TAG} //src/api-server/cmd:push_api-server_image
        working-directory: .

