name: release-dev-images

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY_SERVER_ADDRESS: ghcr.io/jaredtan95
  REGISTRY_USER_NAME: ${{ github.repository_owner }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}

jobs:
  release-images:
    # This matches the dev_image and base image used in the code base.
    runs-on: ubuntu-22.04
    container:
      image: public.ecr.aws/tricorder/ci_image:202302140538
      options: --privileged
      volumes:
        # Needed for accessing kernel headers
        - /usr/src:/usr/src
        # Needed for accessing kernel headers
        - /:/host:ro
        # Needed to access /sys/kernel/tracing/kprobe
        - /sys/kernel:/sys/kernel
    permissions:
      contents: read
      packages: write
    timeout-minutes: 90
    env:
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract tag
        if: contains(github.ref, '/tags/')
        # override TAG with git tag
        run: echo "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACTIONS_TOKEN }}
      - name: Build and push starship api-server image
        run: bazel run -c opt --define=TAG=${TAG} --define=REGISTRY=${REGISTRY_SERVER_ADDRESS} //src/api-server/cmd:push_api-server_image
        working-directory: .
        # aws cli for agent download linux kernal headers packages
      - uses: chrislennon/action-aws-cli@v1.1
      - name: Build and push starship agent image
        run: bazel run -c opt --define=TAG=${TAG} --define=REGISTRY=${REGISTRY_SERVER_ADDRESS} //src/agent/cmd:push_agent_image
        working-directory: .
      # - name: Login to Another Package Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: docker.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.ACTIONS_TOKEN }}
      # - name: Docker tag and push
      #   # TODO(jian): docker tag api-server, agent, ui to another registry and push
      #   run: |
      #     docker tag ${REGISTRY_SERVER_ADDRESS}/agent:${TAG} another-registry/agent:${TAG} && docker push another-registry/agent:${TAG}
      #     docker tag ${REGISTRY_SERVER_ADDRESS}/api-server:${TAG} another-registry/api-server:${TAG} && docker push another-registry/api-server:${TAG}

